### ISSUE TITLE
Add a loader instead of Text

### ISSUE THREAD

**Issue by PriyaBihani** [MLH-Fellowship/prep-project-4.1.3#13]

**Comment by sumana2001** [comment]
Hey @PriyaBihani @grace-omotoso 
In the recently deployed version as soon as I am trying to type anything it is starting the preloader and not ending. I am not able to understand what the exact issue is though.


https://user-images.githubusercontent.com/63084088/142400352-db454c69-904b-47a4-90b1-c4c1b85480ae.mov

**Comment by grace-omotoso** [comment]
@PriyaBihani please, take a look at the issue

**Comment by saikeshari** [comment]
@sumana2001 Here whenever we start typing in the input, it hits the API, so whenever we will start typing and it will send the first letter as query to API, it wouldn't fetch any results and thus, never setting isLoaded as true.
So instead of onChange in the input, we have to make it onSubmit and a submit button beside it.

**Comment by sumana2001** [comment]
@saikeshari One small suggestion, let me know what you think about it. Since this loader is cover the entire screen, it looks like the page is getting refreshed. Will it be better if we make this either a preloader or somehow create an effect where only that weather section of the website has a loader effect and not the entire thing? I hope it makes sense

**Comment by saikeshari** [comment]
Yes it can be done. It will be better actually as we could change the input while loader is there thus, solving the above problem.
